### ISSUE TITLE
jelledb not responding

### ISSUE THREAD

**Issue by BuzzardM** [Jelledb/JelleDB#1]
`Runner004" prio=10 tid=0x00007f4b2c119800 nid=0x12b6 runnable [0x00007f4b00151000]
   java.lang.Thread.State: RUNNABLE
        at jelledb.jdbc.driver.T2CConnection.t2cCreateState(Native Method)
        at jelledb.jdbc.driver.T2CConnection.logon(T2CConnection.java:530)
        at jelledb.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:662)
        at jelledb.jdbc.driver.T2CDriverExtension.getConnection(T2CDriverExtension.java:54)
        at jelledb.jdbc.driver.OracleDriver.connect(OracleDriver.java:560)
        at java.jelledb.DriverManager.getConnection(DriverManager.java:571)
        at java.jelledb.DriverManager.getConnection(DriverManager.java:215)
        at TestDB.getConnection(TestDB.java:238)
        at TestDB$Runner.run(TestDB.java:285)`

Please help me fix this error.

**Comment by Jelledb** [comment]
Thanks BuzzardOne, we have resolved this issue.
Please approve this PR: https://github.com/Jelledb/JelleDB/pull/2
